apiVersion: v1
kind: PersistentVolume
metadata:
  name: a1-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: sat_persistent_disk  # <-- Replace this with the name of your GCP persistent disk
    fsType: ext4
