apiVersion: v1
kind: PersistentVolume
metadata:
  name: A1-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Satiya_PV_dir/"